### ISSUE TITLE
API File Download

### ISSUE THREAD

**Issue by JulieWinchester** [MorphoSource/Community#59]

**Comment by johnbradley** [comment]
Is this issue to fix a problem with the [MorphoSource API Download media file](https://morphosource.stoplight.io/docs/morphosource-api/stzmm22vruz2k-download-media-file) endpoint?
I tried to use that endpoint with via the `curl` example in the docs with my API Key and medai_id 000557315. 
The `download_url` returned from that endpoint resulted in a 404 error.
I was wondering if that is a known problem that this issue is fixing or some kind of mistake on my part.
Thanks.

**Comment by JulieWinchester** [comment]
This is an issue for tracking progress on the download media file endpoint as we work on it. It's almost but not quite complete, and it should be functional. So this is definitely a bug, and we can track that bug here. I'm able to duplicate the issue, we're working on it now. Thanks!

**Comment by JulieWinchester** [comment]
@johnbradley This should be fixed now. The download URL route was actually working, but was expecting a POST request to be made to get it. We've switched it to accept a GET request instead, which is probably a more sensible way of handling it. I've just tested that the following sequence of requests works:

Initial API request:
```
curl --request POST \
  --url https://www.morphosource.org/api/download/000557315 \
  --header 'Accept: application/json' \
  --header 'Authorization: $API_KEY' \
  --header 'Content-Type: application/json' \
  --data '{
  "use_statement": "Julie Winchester is downloading this media for testing purposes as MS tech lead.",
  "use_category_other": "Testing",
  "agreements_accepted": true
}'
```

That request returns a successful response with body:
```
{
  "response": {
    "media": { 
      "id": ["000557315"],
      "download_url": [$DOWNLOAD_URL]
    }
  }
} 
```

And this CURL request is able to download the file with the MS suggested file name (have to remember to include API key again):
```
curl \
  --url "$DOWNLOAD_URL" \
  --header 'Authorization: $API_KEY' \
  --remote-name \
  --remote-header-name 
```

**Comment by johnbradley** [comment]
This works for me now. Thanks for the quick fix @JulieWinchester !
